### Expt-5 : Disease Prediction using Naive Bayes and Neural Network with Comparison of Classifiers

# Name : Nihar Naringrekar       Roll No : 48        Date : 16/02/2026

In [29]:
!pip install scikit.learn
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

In [30]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split 

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier 
from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_auc_score,confusion_matrix,classification_report 

In [31]:
data = load_breast_cancer()

x = data.data
y = data.target

print("Classes:",data.target_names)

x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size=0.3)

Classes: ['malignant' 'benign']


## Table-A: Training and Test Accuracy (Learning Behaviour of ML Model)

### Logistic Regression

In [32]:
lr = LogisticRegression(max_iter=5000)
lr.fit(x_train, y_train)

pred_lr = lr.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_lr))
pred_lr_train = lr.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_lr_train))

Accuracy_test: 0.9473684210526315
Accuracy_train: 0.9748743718592965


## Decision Tree

In [33]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)

pred_dt = dt.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_dt))
pred_dt_train = dt.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_dt_train))

Accuracy_test: 0.9181286549707602
Accuracy_train: 1.0


## KNN

In [34]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)

pred_knn = knn.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_dt))
pred_knn_train = knn.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_knn_train))

Accuracy_test: 0.9181286549707602
Accuracy_train: 0.9547738693467337


## GaussianNB

In [35]:
Gnb = GaussianNB()
Gnb.fit(x_train, y_train)

pred_Gnb = Gnb.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_Gnb))
pred_Gnb_train = Gnb.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_Gnb_train))

Accuracy_test: 0.9298245614035088
Accuracy_train: 0.9522613065326633


## MLP Classifier

In [36]:
mlpc = MLPClassifier()
mlpc.fit(x_train, y_train)

pred_mlpc = mlpc.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_mlpc))
pred_mlpc_train = mlpc.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_mlpc_train))

Accuracy_test: 0.9122807017543859
Accuracy_train: 0.9547738693467337


C:\Users\HP\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# Table B : Classification Performance Metrics (Threshold-based Evaluation)

## Logistic Regression

In [39]:
precision_lr = precision_score(y_test ,pred_lr)
recall_lr = recall_score(y_test, pred_lr)
f1_lr = f1_score (y_test, pred_lr)
roc_lr = roc_auc_score(y_test , pred_lr)

print("precision:", precision_lr)
print("recall:", recall_lr)
print("f1-score", f1_lr)
print("ROC AUS:", roc_lr)

precision: 0.9380530973451328
recall: 0.9814814814814815
f1-score 0.9592760180995475
ROC AUS: 0.9351851851851851


## Decision Tree

In [40]:
precision_dt = precision_score(y_test ,pred_dt)
recall_dt = recall_score(y_test, pred_dt)
f1_dt = f1_score (y_test, pred_dt)
roc_dt = roc_auc_score(y_test , pred_dt)

print("precision:", precision_dt)
print("recall:", recall_dt)
print("f1-score", f1_dt)
print("ROC AUS:", roc_dt)

precision: 0.9519230769230769
recall: 0.9166666666666666
f1-score 0.9339622641509433
ROC AUS: 0.9186507936507936


## KNN

In [41]:
precision_knn = precision_score(y_test ,pred_knn)
recall_knn = recall_score(y_test, pred_knn)
f1_knn = f1_score (y_test, pred_knn)
roc_knn = roc_auc_score(y_test , pred_knn)

print("precision:", precision_knn)
print("recall:", recall_knn)
print("f1-score", f1_knn)
print("ROC AUS:", roc_knn)

precision: 0.918918918918919
recall: 0.9444444444444444
f1-score 0.9315068493150684
ROC AUS: 0.9007936507936508


## GaussianNB

In [44]:
precision_Gnb = precision_score(y_test ,pred_Gnb)
recall_Gnb = recall_score(y_test, pred_Gnb)
f1_Gnb = f1_score (y_test, pred_Gnb)
roc_Gnb = roc_auc_score(y_test , pred_Gnb)

print("precision:", precision_Gnb)
print("recall:", recall_Gnb)
print("f1-score", f1_Gnb)
print("ROC AUS:", roc_Gnb)

precision: 0.9210526315789473
recall: 0.9722222222222222
f1-score 0.9459459459459458
ROC AUS: 0.9146825396825398


## MLP Classifier 

In [45]:
precision_mlpc = precision_score(y_test ,pred_mlpc)
recall_mlpc = recall_score(y_test, pred_mlpc)
f1_mlpc = f1_score (y_test, pred_mlpc)
roc_mlpc = roc_auc_score(y_test , pred_mlpc)

print("precision:", precision_mlpc)
print("recall:", recall_mlpc)
print("f1-score", f1_mlpc)
print("ROC AUS:", roc_mlpc)

precision: 0.8974358974358975
recall: 0.9722222222222222
f1-score 0.9333333333333333
ROC AUS: 0.8908730158730159


## Table C : Confusion Matrix and Error Analysis

## Logistic Regression

In [47]:
cm_lr=confusion_matrix(y_test,pred_lr)
print("decision tree confusion matrix:")
print(cm_lr)
TN2,FP2,FN2,TP2 = cm_lr.ravel()
type1_lr=FP2/(FP2+TN2)
type2_lr=FN2/(FN2+FP2)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_dt*100)
print("type2 error rate in %:",type2_dt*100)


decision tree confusion matrix:
[[ 56   7]
 [  2 106]]
FP(type1): 7
FN(type2): 2
type1 error rate in %: 7.936507936507936
type2 error rate in %: 64.28571428571429


## Decision Tree

In [48]:
cm_dt=confusion_matrix(y_test,pred_dt)
print("decision tree confusion matrix:")
print(cm_dt)
TN2,FP2,FN2,TP2 = cm_dt.ravel()
type1_dt=FP2/(FP2+TN2)
type2_dt=FN2/(FN2+FP2)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_dt*100)
print("type2 error rate in %:",type2_dt*100)


decision tree confusion matrix:
[[58  5]
 [ 9 99]]
FP(type1): 5
FN(type2): 9
type1 error rate in %: 7.936507936507936
type2 error rate in %: 64.28571428571429


## KNN

In [49]:
cm_knn=confusion_matrix(y_test,pred_dt)
print("decision tree confusion matrix:")
print(cm_knn)
TN2,FP2,FN2,TP2 = cm_knn.ravel()
type1_knn=FP2/(FP2+TN2)
type2_knn=FN2/(FN2+FP2)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_dt*100)
print("type2 error rate in %:",type2_dt*100)


decision tree confusion matrix:
[[58  5]
 [ 9 99]]
FP(type1): 5
FN(type2): 9
type1 error rate in %: 7.936507936507936
type2 error rate in %: 64.28571428571429


## Gaussian NB

In [50]:
cm_Gnb=confusion_matrix(y_test,pred_Gnb)
print("decision tree confusion matrix:")
print(cm_Gnb)
TN2,FP2,FN2,TP2 = cm_Gnb.ravel()
type1_Gnb=FP2/(FP2+TN2)
type2_Gnb=FN2/(FN2+FP2)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_Gnb*100)
print("type2 error rate in %:",type2_Gnb*100)

decision tree confusion matrix:
[[ 54   9]
 [  3 105]]
FP(type1): 9
FN(type2): 3
type1 error rate in %: 14.285714285714285
type2 error rate in %: 25.0


## MLP classifier

In [51]:
cm_mlpc=confusion_matrix(y_test,pred_mlpc)
print("decision tree confusion matrix:")
print(cm_mlpc)
TN2,FP2,FN2,TP2 = cm_mlpc.ravel()
type1_mlpc=FP2/(FP2+TN2)
type2_mlpc=FN2/(FN2+FP2)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_mlpc*100)
print("type2 error rate in %:",type2_mlpc*100)


decision tree confusion matrix:
[[ 51  12]
 [  3 105]]
FP(type1): 12
FN(type2): 3
type1 error rate in %: 19.047619047619047
type2 error rate in %: 20.0
