### Expt-5 : Disease Prediction using Naive Bayes and Neural Network with Comparison of Classifiers

# Name : Nihar Naringrekar       Roll No : 48        Date : 16/02/2026

In [49]:
!pip install scikit.learn
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

In [50]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_auc_score,confusion_matrix,classification_report

In [51]:
data = load_breast_cancer()

x = data.data
y = data.target

print("Classes:",data.target_names)

x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size=0.3)

Classes: ['malignant' 'benign']


## Table-A: Training and Test Accuracy (Learning Behaviour of ML Model)

### Logistic Regression

In [52]:
lr = LogisticRegression(max_iter=5000)
lr.fit(x_train, y_train)

pred_lr = lr.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_lr))
pred_lr_train = lr.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_lr_train))

Accuracy_test: 0.935672514619883
Accuracy_train: 0.9723618090452262


## Decision Tree

In [53]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)

pred_dt = dt.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_dt))
pred_dt_train = dt.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_dt_train))

Accuracy_test: 0.9239766081871345
Accuracy_train: 1.0


## KNN

In [54]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)

pred_knn = knn.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_dt))
pred_knn_train = knn.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_knn_train))

Accuracy_test: 0.9239766081871345
Accuracy_train: 0.9346733668341709


## GaussianNB

In [55]:
Gnb = GaussianNB()
Gnb.fit(x_train, y_train)

pred_Gnb = Gnb.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_Gnb))
pred_Gnb_train = Gnb.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_Gnb_train))

Accuracy_test: 0.9415204678362573
Accuracy_train: 0.9396984924623115


## MLP Classifier

In [56]:
mlpc = MLPClassifier()
mlpc.fit(x_train, y_train)

pred_mlpc = mlpc.predict(x_test)

print("Accuracy_test:" , accuracy_score (y_test, pred_mlpc))
pred_mlpc_train = mlpc.predict(x_train)
print("Accuracy_train:",accuracy_score (y_train,pred_mlpc_train))

Accuracy_test: 0.935672514619883
Accuracy_train: 0.9271356783919598


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# Table B : Classification Performance Metrics (Threshold-based Evaluation)

## Logistic Regression

In [57]:
precision_lr = precision_score(y_test ,pred_lr)
recall_lr = recall_score(y_test, pred_lr)
f1_lr = f1_score (y_test, pred_lr)
roc_lr = roc_auc_score(y_test , pred_lr)

print("precision:", precision_lr)
print("recall:", recall_lr)
print("f1-score", f1_lr)
print("ROC AUS:", roc_lr)

precision: 0.9711538461538461
recall: 0.926605504587156
f1-score 0.9483568075117371
ROC AUS: 0.9391092039064812


## Decision Tree

In [58]:
precision_dt = precision_score(y_test ,pred_dt)
recall_dt = recall_score(y_test, pred_dt)
f1_dt = f1_score (y_test, pred_dt)
roc_dt = roc_auc_score(y_test , pred_dt)

print("precision:", precision_dt)
print("recall:", recall_dt)
print("f1-score", f1_dt)
print("ROC AUS:", roc_dt)

precision: 0.9363636363636364
recall: 0.944954128440367
f1-score 0.9406392694063926
ROC AUS: 0.9160254513169576


## KNN

In [59]:
precision_knn = precision_score(y_test ,pred_knn)
recall_knn = recall_score(y_test, pred_knn)
f1_knn = f1_score (y_test, pred_knn)
roc_knn = roc_auc_score(y_test , pred_knn)

print("precision:", precision_knn)
print("recall:", recall_knn)
print("f1-score", f1_knn)
print("ROC AUS:", roc_knn)

precision: 0.9537037037037037
recall: 0.944954128440367
f1-score 0.9493087557603687
ROC AUS: 0.9321544835750221


## GaussianNB

In [60]:
precision_Gnb = precision_score(y_test ,pred_Gnb)
recall_Gnb = recall_score(y_test, pred_Gnb)
f1_Gnb = f1_score (y_test, pred_Gnb)
roc_Gnb = roc_auc_score(y_test , pred_Gnb)

print("precision:", precision_Gnb)
print("recall:", recall_Gnb)
print("f1-score", f1_Gnb)
print("ROC AUS:", roc_Gnb)

precision: 0.9380530973451328
recall: 0.9724770642201835
f1-score 0.954954954954955
ROC AUS: 0.9297869192068658


## MLP Classifier

In [61]:
precision_mlpc = precision_score(y_test ,pred_mlpc)
recall_mlpc = recall_score(y_test, pred_mlpc)
f1_mlpc = f1_score (y_test, pred_mlpc)
roc_mlpc = roc_auc_score(y_test , pred_mlpc)

print("precision:", precision_mlpc)
print("recall:", recall_mlpc)
print("f1-score", f1_mlpc)
print("ROC AUS:", roc_mlpc)

precision: 0.9375
recall: 0.963302752293578
f1-score 0.9502262443438914
ROC AUS: 0.9251997632435631


## Table C : Confusion Matrix and Error Analysis

## Logistic Regression

In [62]:
cm_lr=confusion_matrix(y_test,pred_lr)
print("logistic confusion matrix:")
print(cm_lr)
TN1, FP1, FN1, TP1  = cm_lr.ravel()
type1_lr=FP1/(FP1+TN1)
type2_lr=FN1/(FN1+TP1)

print("FP(type1):",FP1)
print("FN(type2):",FN1)
print("type1 error rate in %:",type1_lr*100)
print("type2 error rate in %:",type2_lr*100)


logistic confusion matrix:
[[ 59   3]
 [  8 101]]
FP(type1): 3
FN(type2): 8
type1 error rate in %: 4.838709677419355
type2 error rate in %: 7.339449541284404


## Decision Tree

In [68]:
cm_dt=confusion_matrix(y_test,pred_dt)
print("decision tree confusion matrix:")
print(cm_dt)
TN2,FP2,FN2,TP2 = cm_dt.ravel()
type1_dt=FP2/(FP2+TN2)
type2_dt=FN2/(FN2+TP2)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_dt*100)
print("type2 error rate in %:",type2_dt*100)


decision tree confusion matrix:
[[ 55   7]
 [  6 103]]
FP(type1): 7
FN(type2): 6
type1 error rate in %: 11.29032258064516
type2 error rate in %: 5.5045871559633035


## KNN

In [64]:
cm_knn=confusion_matrix(y_test,pred_dt)
print("knn confusion matrix:")
print(cm_knn)
TN3, FP3, FN3, TP3 = cm_knn.ravel()
type1_knn=FP3/(FP3+TN3)
type2_knn=FN3/(FN3+TP3)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_knn*100)
print("type2 error rate in %:",type2_knn*100)


knn confusion matrix:
[[ 55   7]
 [  6 103]]
FP(type1): 7
FN(type2): 6
type1 error rate in %: 11.29032258064516
type2 error rate in %: 5.5045871559633035


## Gaussian NB

In [65]:
cm_Gnb=confusion_matrix(y_test,pred_Gnb)
print("Gaussian confusion matrix:")
print(cm_Gnb)
TN4, FP4, FN4, TP4 = cm_Gnb.ravel()
type1_Gnb=FP4/(FP4+TN4)
type2_Gnb=FN4/(FN4+TP4)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_Gnb*100)
print("type2 error rate in %:",type2_Gnb*100)

Gaussian confusion matrix:
[[ 55   7]
 [  3 106]]
FP(type1): 7
FN(type2): 6
type1 error rate in %: 11.29032258064516
type2 error rate in %: 2.7522935779816518


## MLP classifier

In [66]:
cm_mlpc=confusion_matrix(y_test,pred_mlpc)
print("MLP classifier confusion matrix:")
print(cm_mlpc)
TN5, FP5, FN5, TP5 = cm_mlpc.ravel()
type1_mlpc=FP5/(FP5+TN5)
type2_mlpc=FN5/(FN5+TP5)

print("FP(type1):",FP2)
print("FN(type2):",FN2)
print("type1 error rate in %:",type1_mlpc*100)
print("type2 error rate in %:",type2_mlpc*100)


MLP classifier confusion matrix:
[[ 55   7]
 [  4 105]]
FP(type1): 7
FN(type2): 6
type1 error rate in %: 11.29032258064516
type2 error rate in %: 3.669724770642202
